version: '3.8'
services:
  db1:
    image: postgres:12.9
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '11000:5432'
    volumes: 
      - db1:/var/lib/postgresql/data
  db2:
      image: postgres:12.9
      restart: always
      environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
      ports:
       - '12000:5432'
      volumes: 
       - db2:/var/lib/postgresql/data
  bucardo:
    image: postgres:12.9
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '13000:5432'
    volumes: 
      - db3:/var/lib/postgresql/data

volumes:
  db1:
    driver: local
  db2:
    driver: local
  db3:
    driver: local
